### ISSUE TITLE
struct variables are not recognized

### ISSUE THREAD

**Issue by jodinathan** [angel-dart/graphql#11]
You can't pass struct as variables, example:

```
query something {
  event(someProp: {
    myInnerProp: 123
  }) {
  ...
  }
}
```

but raw variables are ok with the parser:

```
query something {
  event(someProp: 123) {
  ...
  }
}
```

**Comment by thosakwe** [comment]
That's surprising. The parser is definitely capable of parsing object values:
https://github.com/angel-dart/graphql/blob/master/graphql_parser/test/value_test.dart#L51-L55

On a closer look, though, it looks like I missed this in my unit tests:
https://github.com/angel-dart/graphql/blob/master/graphql_parser/test/argument_test.dart#L10

**Comment by thosakwe** [comment]
Are you still experiencing this? The `modify_human` field in `example_star_wars` incorporates this, and I don't get any such error.
