### ISSUE TITLE
Support annotating a Dart class to generate a schema

### ISSUE THREAD

**Issue by kevmoo** [angel-dart/graphql#14]
It'd be super nice!

**Comment by thosakwe** [comment]
It's actually already supported in `package:graphql_server/mirrors.dart` - there's a `convertDartType` function that uses mirrors. I considered going to source_gen route, but I figure that it's more than likely that this package will only be used on the VM.

https://github.com/angel-dart/graphql/blob/master/graphql_server/lib/mirrors.dart

**Comment by thosakwe** [comment]
I'll keep this open for now, though. Down the line, it might be necessary to also provide some kind of `source_gen` support. Guess it depends on which use cases become common.

**Comment by kevmoo** [comment]
I could imagine wanting browser (JS) clients for this. Also, dart:mirrors
is not an option on Flutter.

**Comment by thosakwe** [comment]
That’s true... I’ll just leave this open for now.

**Comment by kevmoo** [comment]
Exciting!

**Comment by thosakwe** [comment]
Work is done, and the existing mirrors-based options are now deprecated. Next up is documentation + getting all the other moving parts to work, and then releasing this, along with Angel 2.
