### ISSUE TITLE
question regarding graphQL gateway

### ISSUE THREAD

**Issue by ghost** [angel-dart/graphql#16]
From what i can see Dart / Angel might be an excellent candidate for microservices architecture.

My Use case:
Have many Microservices that are graphql ( written in many languages ) but each has a graphql schema, and so MAYBE with Dart we can make a reflection based gateway that when it gets a GraphQL query / mutation, can manage calling the microservices to fulfil the query / mutation,
The idea is for the Gateway to be very DUMB and require just a few strings.

Dart VM has nice reflection / mirrors and might be able to do this.

**Comment by thosakwe** [comment]
I think that should be possible. Have you tried the `convertDartType` function? It creates a schema from any Dart type.

**Comment by thosakwe** [comment]
Also, check out `graphql_generator` (I intend to write its documentation today):
https://github.com/angel-dart/graphql/tree/master/graphql_generator

**Comment by gedw99** [comment]
thanks @thosakwe 
Will have a look at that !!
