### ISSUE TITLE
[Proposal] Switch to GraphQL Playground

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [angel-dart/graphql#36]
Would it be an issue to switch to using [Prisma's GraphQL Playground](https://github.com/prisma-labs/graphql-playground) instead of GraphiQL? I think it looks better, at least. If not officially supported, any ideas on how I can switch it in?

**Comment by ThinkDigitalSoftware** [comment]
I forgot to mention how AMAZED I am at all the work you've done, devotion to the community and the sheer number of packages that you have!

**Comment by thosakwe** [comment]
Thanks! Appreciate it. I thought I had responded to this via email, but I guess it didn't send.

I agree, GraphQL Playground looks better, but I simply didn't know it existed at the time. The usage seems pretty similar, though, so I could probably take a pull request to add this to `angel_graphql`.

**Comment by thosakwe** [comment]
As of `angel_graphql@2.0.0-beta`, you can now use the `graphQLPlayground(...)` request handler, which has identical usage to `graphiql(...)`:

```dart
app.all('/graphql', graphQLHttp(GraphQL(schema)));
app.get('/graphiql', graphiQL());
app.get('/playground', graphQLPlayground());
```

https://pub.dev/packages/angel_graphql/versions/2.0.0-beta

![Screen Shot 2020-02-04 at 10 30 34 AM](https://user-images.githubusercontent.com/9996860/73759207-9b27b480-4739-11ea-98ce-db9968ba7ab2.png)

**Comment by ThinkDigitalSoftware** [comment]
Awesome! Thank you
