### ISSUE TITLE
Consider mono_repo for managing multiple dart packages in one repo

### ISSUE THREAD

**Issue by kevmoo** [angel-dart/graphql#8]
https://pub.dartlang.org/packages/mono_repo

See https://github.com/dart-lang/json_serializable/blob/master/json_serializable/.mono_repo.yml
https://github.com/dart-lang/json_serializable/blob/master/.travis.yml

Etc...

**Comment by thosakwe** [comment]
Resolved in https://github.com/angel-dart/graphql/commit/ff2aa03784cd111f3efe19e84233e2972c3e6b14
